# Generated by Django 6.0.7 on 2026-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=50, unique=True)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(max_length=255)),
                ('route_type', models.IntegerField(default=3)),
                ('city', models.CharField(default='Delhi', max_length=100)),
            ],
        ),
    ]
